// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/customer.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomerDetails struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerDetails) Reset()         { *m = CustomerDetails{} }
func (m *CustomerDetails) String() string { return proto.CompactTextString(m) }
func (*CustomerDetails) ProtoMessage()    {}
func (*CustomerDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b01af02e6454e3a1, []int{0}
}

func (m *CustomerDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerDetails.Unmarshal(m, b)
}
func (m *CustomerDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerDetails.Marshal(b, m, deterministic)
}
func (m *CustomerDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerDetails.Merge(m, src)
}
func (m *CustomerDetails) XXX_Size() int {
	return xxx_messageInfo_CustomerDetails.Size(m)
}
func (m *CustomerDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerDetails proto.InternalMessageInfo

func (m *CustomerDetails) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CustomerDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CustomerDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerDetails) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CustomerDetails) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CustomerRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerRequest) Reset()         { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()    {}
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b01af02e6454e3a1, []int{1}
}

func (m *CustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest.Unmarshal(m, b)
}
func (m *CustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest.Marshal(b, m, deterministic)
}
func (m *CustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest.Merge(m, src)
}
func (m *CustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest.Size(m)
}
func (m *CustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest proto.InternalMessageInfo

func (m *CustomerRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CustomerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Acknowledgement struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_b01af02e6454e3a1, []int{2}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Acknowledgement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerDetails)(nil), "v1.CustomerDetails")
	proto.RegisterType((*CustomerRequest)(nil), "v1.CustomerRequest")
	proto.RegisterType((*Acknowledgement)(nil), "v1.Acknowledgement")
}

func init() { proto.RegisterFile("proto/v1/customer.proto", fileDescriptor_b01af02e6454e3a1) }

var fileDescriptor_b01af02e6454e3a1 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0xc4, 0x30,
	0x18, 0xc4, 0xb7, 0xdd, 0x3f, 0xe2, 0x27, 0xac, 0xf2, 0x29, 0x18, 0x3c, 0x49, 0x4f, 0x9e, 0xba,
	0xd4, 0x3d, 0x09, 0x5e, 0x64, 0x05, 0xef, 0xeb, 0x13, 0xc4, 0x66, 0xd0, 0x60, 0xdb, 0xd4, 0x24,
	0x1b, 0xdf, 0x41, 0xf0, 0x9d, 0xa5, 0x69, 0x17, 0x75, 0x11, 0xdc, 0xdb, 0xcc, 0x8f, 0x19, 0x98,
	0xe4, 0xa3, 0xf3, 0xd6, 0x1a, 0x6f, 0x16, 0xa1, 0x58, 0x94, 0x1b, 0xe7, 0x4d, 0x0d, 0x9b, 0x47,
	0xc2, 0x69, 0x28, 0xb2, 0xcf, 0x84, 0x8e, 0x57, 0x03, 0xbe, 0x87, 0x97, 0xba, 0x72, 0x7c, 0x42,
	0x63, 0xd9, 0x6a, 0x91, 0x5c, 0x26, 0x57, 0x87, 0xeb, 0x4e, 0xf2, 0x9c, 0x52, 0xad, 0x44, 0x1a,
	0x41, 0xaa, 0x15, 0x33, 0x4d, 0x1a, 0x59, 0x43, 0x8c, 0x23, 0x89, 0x9a, 0xcf, 0x68, 0x8a, 0x5a,
	0xea, 0x4a, 0x4c, 0x22, 0xec, 0x0d, 0x0b, 0x3a, 0x90, 0x4a, 0x59, 0x38, 0x27, 0xa6, 0x91, 0x6f,
	0x6d, 0x97, 0x6f, 0x5f, 0x4c, 0x03, 0x31, 0xeb, 0xf3, 0xd1, 0x64, 0xcb, 0xef, 0x39, 0x6b, 0xbc,
	0x6d, 0xe0, 0xfc, 0xff, 0x73, 0xba, 0xd2, 0x5d, 0xf9, 0xda, 0x98, 0xf7, 0x0a, 0xea, 0x19, 0x35,
	0x9a, 0x3d, 0x4a, 0xd7, 0x1f, 0x3f, 0x5e, 0xfe, 0x08, 0x1b, 0x74, 0x09, 0xbe, 0xa1, 0xa3, 0x07,
	0xf8, 0x2d, 0xe5, 0xd3, 0x3c, 0x14, 0xf9, 0xce, 0x9c, 0x8b, 0x5f, 0x70, 0xf8, 0xb2, 0x6c, 0xc4,
	0xb7, 0x34, 0x5f, 0x59, 0x48, 0x8f, 0xbf, 0xdb, 0x43, 0xb0, 0x6f, 0xef, 0x8c, 0xcd, 0x46, 0x4f,
	0xb3, 0x78, 0x91, 0xe5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x19, 0x2a, 0xb9, 0xac, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	GetCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerDetails, error)
	CreateCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) GetCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerDetails, error) {
	out := new(CustomerDetails)
	err := c.cc.Invoke(ctx, "/v1.CustomerService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/v1.CustomerService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	GetCustomer(context.Context, *CustomerRequest) (*CustomerDetails, error)
	CreateCustomer(context.Context, *CustomerDetails) (*Acknowledgement, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) GetCustomer(ctx context.Context, req *CustomerRequest) (*CustomerDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (*UnimplementedCustomerServiceServer) CreateCustomer(ctx context.Context, req *CustomerDetails) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CustomerService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*CustomerDetails))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomer",
			Handler:    _CustomerService_GetCustomer_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/customer.proto",
}
