// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/notify.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomerDetails struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerDetails) Reset()         { *m = CustomerDetails{} }
func (m *CustomerDetails) String() string { return proto.CompactTextString(m) }
func (*CustomerDetails) ProtoMessage()    {}
func (*CustomerDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e023563da9578504, []int{0}
}

func (m *CustomerDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerDetails.Unmarshal(m, b)
}
func (m *CustomerDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerDetails.Marshal(b, m, deterministic)
}
func (m *CustomerDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerDetails.Merge(m, src)
}
func (m *CustomerDetails) XXX_Size() int {
	return xxx_messageInfo_CustomerDetails.Size(m)
}
func (m *CustomerDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerDetails proto.InternalMessageInfo

func (m *CustomerDetails) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CustomerDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CustomerDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerDetails) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CustomerDetails) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Acknowledgement struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_e023563da9578504, []int{1}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Acknowledgement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerDetails)(nil), "v1.CustomerDetails")
	proto.RegisterType((*Acknowledgement)(nil), "v1.Acknowledgement")
}

func init() { proto.RegisterFile("proto/v1/notify.proto", fileDescriptor_e023563da9578504) }

var fileDescriptor_e023563da9578504 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0x6d, 0xee, 0x8f, 0x38, 0xa0, 0x57, 0x46, 0x85, 0xe0, 0x4a, 0xba, 0x72, 0xd5, 0x4b,
	0xbd, 0x2f, 0xa0, 0x5c, 0xd7, 0x82, 0xfa, 0x04, 0xb1, 0x19, 0x75, 0xb0, 0x49, 0x4a, 0x12, 0x23,
	0x3e, 0x84, 0xef, 0x2c, 0x9d, 0xe2, 0xa6, 0x1b, 0x77, 0xe7, 0xfb, 0x38, 0x90, 0x9c, 0x81, 0x8b,
	0x21, 0x86, 0x1c, 0xb6, 0xa5, 0xdd, 0xfa, 0x90, 0xf9, 0xf5, 0xbb, 0x11, 0x46, 0x55, 0xda, 0xfa,
	0xa7, 0x82, 0xcd, 0xfe, 0x33, 0xe5, 0xe0, 0x28, 0xde, 0x53, 0x36, 0xdc, 0x27, 0x3c, 0x85, 0x85,
	0x19, 0x58, 0x57, 0x57, 0xd5, 0xf5, 0xd1, 0xd3, 0x18, 0xf1, 0x04, 0x14, 0x5b, 0xad, 0x44, 0x28,
	0xb6, 0x88, 0xb0, 0xf4, 0xc6, 0x91, 0x5e, 0x88, 0x91, 0x8c, 0xe7, 0xb0, 0x22, 0x67, 0xb8, 0xd7,
	0x4b, 0x91, 0x13, 0xa0, 0x86, 0x43, 0x63, 0x6d, 0xa4, 0x94, 0xf4, 0x4a, 0xfc, 0x1f, 0x8e, 0xfd,
	0xe1, 0x3d, 0x78, 0xd2, 0xeb, 0xa9, 0x2f, 0x50, 0xef, 0x60, 0x73, 0xd7, 0x7d, 0xf8, 0xf0, 0xd5,
	0x93, 0x7d, 0x23, 0x47, 0x3e, 0xff, 0xff, 0x9d, 0x9b, 0x47, 0x38, 0x7e, 0x90, 0x61, 0xcf, 0x14,
	0x0b, 0x77, 0x84, 0xb7, 0x80, 0xfb, 0x48, 0x26, 0x93, 0x68, 0xee, 0x4c, 0xe6, 0xe0, 0xf1, 0xac,
	0x29, 0x6d, 0x33, 0x1b, 0x7b, 0x29, 0x72, 0xf6, 0x64, 0x7d, 0xf0, 0xb2, 0x96, 0x13, 0xed, 0x7e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xb5, 0x8b, 0x6a, 0x3b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyServiceClient interface {
	CreateNotification(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type notifyServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotifyServiceClient(cc *grpc.ClientConn) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) CreateNotification(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/v1.NotifyService/CreateNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
type NotifyServiceServer interface {
	CreateNotification(context.Context, *CustomerDetails) (*Acknowledgement, error)
}

// UnimplementedNotifyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotifyServiceServer struct {
}

func (*UnimplementedNotifyServiceServer) CreateNotification(ctx context.Context, req *CustomerDetails) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotification not implemented")
}

func RegisterNotifyServiceServer(s *grpc.Server, srv NotifyServiceServer) {
	s.RegisterService(&_NotifyService_serviceDesc, srv)
}

func _NotifyService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NotifyService/CreateNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).CreateNotification(ctx, req.(*CustomerDetails))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotifyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotification",
			Handler:    _NotifyService_CreateNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/notify.proto",
}
